# Generated by Django 5.1.6 on 2025-02-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_transfer_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
