# Generated by Django 5.1.6 on 2025-02-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_remove_letting_address_delete_address_delete_letting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
