name: CI Pipeline

on:
  push:
    branches:
      - master
      - QA
  pull_request:
    branches:
      - master
      - QA

jobs:
  test:
    name: Run Linting, Tests & Compilation
    runs-on: ubuntu-latest
    env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DNS_SENTRY: ${{ secrets.DNS_SENTRY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 (Linting)
        run: |
          flake8 . || exit 1

      - name: Run Pytest with coverage
        run: |
          pytest || exit 1

      - name: Check Coverage >= 80%
        run: |
          pytest --cov-report=term-missing
          coverage report --fail-under=80

  containerize:
    name: Build and push Docker Image
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DNS_SENTRY: ${{ secrets.DNS_SENTRY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Set Docker Image Tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker Image with secrets
        run: |
          docker build \
          --build-arg DJANGO_SECRET_KEY="$DJANGO_SECRET_KEY" \
          --build-arg DNS_SENTRY="$DNS_SENTRY" \
          -t "$DOCKERHUB_USERNAME/oc-lettings-site:${{ env.IMAGE_TAG }}" \
          -t "$DOCKERHUB_USERNAME/oc-lettings-site:latest" .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push "$DOCKERHUB_USERNAME/oc-lettings-site:${{ env.IMAGE_TAG }}"
          docker push "$DOCKERHUB_USERNAME/oc-lettings-site:latest"

  deploy:
    name: Create and Deploy to Render
    if: github.ref == 'refs/heads/master'
    needs: containerize
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DNS_SENTRY: ${{ secrets.DNS_SENTRY }}
      RENDER_OWNER_ID : ${{ secrets.RENDER_OWNER_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Render Service (first-time)
        run: |
          # Create Render service via API
          RESPONSE=$(curl -X POST "https://api.render.com/v1/services" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{
                  "ownerID": "'"$RENDER_OWNER_ID"'",
                  "serviceName": "oc-lettings-site",
                  "env": "docker",
                  "docker": {
                    "image": "'"$DOCKERHUB_USERNAME/oc-lettings-site:latest"'"
                  },
                  "region": "us",
                  "plan": "starter"
                }')
  
          # Afficher la réponse brute pour le débogage
          echo "Response: $RESPONSE"
  
          # Extraire le service_id de la réponse JSON
          SERVICE_ID=$(echo $RESPONSE | jq -r '.id')
  
          if [ "$SERVICE_ID" != "null" ]; then
            echo "Service created with ID: $SERVICE_ID"
            echo "RENDER_SERVICE_ID=$SERVICE_ID" >> $GITHUB_ENV
          else
            echo "Error creating service"
            exit 1
          fi

      - name: Trigger Deploy on Render
        run: |
          # Déployer le service via l'API Render
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{
                  "branch": "master",
                  "dockerImage": "'"$DOCKERHUB_USERNAME/oc-lettings-site:latest"'"
                }'
  
  
