name: CI Pipeline

on:
  push:
    branches:
      - master
      - QA
  pull_request:
    branches:
      - master
      - QA

jobs:
  test:
    name: Run Linting, Tests & Compilation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8 (Linting)
        run: |
          flake8 . || exit 1

      - name: Run Pytest with coverage
        run: |
          pytest || exit 1

      - name: Check Coverage >= 80%
        run: |
          pytest --cov-report=term-missing
          coverage report --fail-under=80

      - name: Collect Django Static Files
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DNS_SENTRY: ${{ secrets.DNS_SENTRY }}
        run: python manage.py collectstatic --noinput

  deploy:
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'  # Se déclenche uniquement sur main
    needs: test  # Ne se lance que si les tests ont réussi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build & push Docker image
        run: echo "Ici, on fera la conteneurisation plus tard"

      - name: Deploy to production
        run: echo "Ici, on fera la mise en production plus tard"
